weights: /home/bird/xuke/st-gcn-master/work_dir/recognition/casia_skeleton/ST_GCN/epoch13_model.pt
#weights: /home/bird/xuke/st-gcn-master/models/st_gcn.kinetics.pt
# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  # #
  data_path:  /home/bird/disk2/mydisk1104/xuke/skeleton-data/casia-skeleton/probe62-090nm-090_data.npy
  label_path:  /home/bird/disk2/mydisk1104/xuke/skeleton-data/casia-skeleton/probe62-090nm-090_label.pkl
  # data_path: ./data/casia/casia-skeleton/train62-018_data.npy
  # label_path: ./data/casia/casia-skeleton/train62-018_label.pkl

# model
model: net.st_gcn_casia.Model
model_args:
  in_channels: 3
  num_class: 62
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'
    # layout: 'casia'
    max_hop: 1

# test
phase: test
device: 1
test_batch_size: 248
